name: Run Spring Boot app in Docker and API tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Spring Boot app repository
        uses: actions/checkout@v3
        with:
          repository: aceton41k/
          path: app

      - name: Build Spring Boot Docker image
        run: |
          docker build -t spring-boot-app:latest ./app

      - name: Create Docker network
        run: docker network create my-network

      - name: Run Spring Boot app container
        run: |
          docker run -d -p 8080:8080 \
            --name spring-boot-app \
            --network my-network \
            --env SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/appdb \
            --env SPRING_DATASOURCE_USERNAME=appuser \
            --env SPRING_DATASOURCE_PASSWORD=appuser123$ \
            spring-boot-app:latest

      - name: Checkout API tests
        uses: actions/checkout@v3
        with:
          path: tests

      - name: Run API tests
        run: |
          cd tests
          ./gradlew test
