name: Run Spring Boot app in Docker and API tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Spring Boot app repository
        uses: actions/checkout@v3
        with:
          repository: aceton41k/spring-boot-app
          path: app

      - name: Checkout API tests
        uses: actions/checkout@v3
        with:
          path: tests

      - name: Set up Docker Compose
        run: |
          sudo apt-get install docker-compose

      - name: Build and start containers
        run: |
          cd app
          docker-compose up -d --build

      - name: Wait for PostgreSQL to be ready
        run: |
          docker-compose exec -T db sh -c 'until pg_isready -U appuser -d appdb; do sleep 1; done'

      - name: Wait for Spring Boot app to be ready
        run: |
          docker-compose exec -T spring-boot-app sh -c 'until curl --fail http://localhost:8080/actuator/health; do sleep 1; done'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run API tests
        run: |
          cd tests
          ./gradlew test --tests template.framework.api.test.AppTests -PskipJooqGeneration -Dapi.url=http://localhost:8080 -Ddb.url=jdbc:postgresql://localhost:5432/appdb -Ddb.password=appuser123$ -Ddb.user=appuser --info

      - name: Stop and remove containers
        run: |
          cd app
          docker-compose down